packages:
  - 'libs/*'

catalog:
  '@types/glob': ^8.1.0
  '@types/css-modules': ^1.0.0
  '@types/react': ^18.3.1
  clsx: ^2.1.1
  glob: ^11.0.0
  react: ^18.3.1
  react-dom: ^18.3.1
  vite: ^5.0.0
  vitest: ^1.3.1
  'vite-tsconfig-paths': ^4.2.0
  '@vitejs/plugin-react': ^4.2.0
  '@vitejs/plugin-react-swc': ^3.0.0
  'vite-plugin-dts': ^4.0.1
  'vite-plugin-svgr': ^4.2.0
  'vite-plugin-turbosnap': ^1.0.3
  'vite-css-modules': ^1.4.2
